# Generated by Django 3.0.6 on 2020-05-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField()),
                ('looks', models.TextField()),
                ('character', models.TextField()),
                ('ability', models.TextField()),
                ('weakness', models.TextField()),
                ('extend', models.TextField()),
            ],
        ),
    ]
